version: "3.4"

networks:
  default:
    name: "votify-network"

services:
  votify-web:
    container_name: votify-web
    image: vcheeney/votify-web
    build: ./web
    env_file: "./web/.env.docker"
    ports:
      - "3000:3000"
    volumes:
      - ./web/prisma:/usr/server/app/prisma

