version: "3.4"

services:
  database:
    image: postgres
    container_name: database
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 6
    ports:
      - "5432:5432"

  local-blockchain:
    container_name: votify-blockchain
    image: vcheeney/votify-blockchain
    build: ./hardhat
    ports:
      - "8545:8545"
